# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: Terraform AWS Provider Bug Reports and Feature Requests
    url: https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose
    about: Terraform AWS Provider specific issues should be raised in the Terraform AWS Provider codebase.
  - name: Terraform AWS Provider Questions
    url: https://discuss.hashicorp.com/c/terraform-providers/tf-aws
    about: GitHub issues in this repository are only intended for bug reports and feature requests. Other issues will be closed. Please ask and answer questions through the Terraform AWS Provider Community Forum.
  - name: Terraform S3 Backend Bug Reports and Feature Requests
    url: https://github.com/hashicorp/terraform/issues/new/choose
    about: Terraform S3 Backend specific issues should be raised in the Terraform Core codebase.
  - name: Terraform S3 Backend, Configuration Language, or Workflow Questions
    url: https://discuss.hashicorp.com/c/terraform-core
    about: Please ask and answer S3 Backend, language, or workflow related questions through the Terraform Core Community Forum.
  - name: Security Vulnerability
    url: https://www.hashicorp.com/security.html
    about: Please report security vulnerabilities responsibly.
