language: go
os: linux
sudo: require
dist: trusty

go:
  - 1.8.3
go_import_path: k8s.io/minikube

install:
  - echo "Don't run anything."
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
