kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: hostpath
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/host-path
