apiVersion: addons.minikube.sigs.k8s.io/v1
kind: Addon
metadata:
  name: falco
spec:
  description: Runtime security monitoring using Falco
  supported_os:
    - linux
  default: false
  requires:
    - kubernetes
  manifests:
    - falco-daemonset.yaml.tmpl
