title = "minikube"
baseURL = "https://minikube.sigs.k8s.io"
enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

 # First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[module]
  [[module.mounts]]
    source = "../deploy/addons/gvisor/"
    target = "content/gvisor/"
  [[module.mounts]]
    source = "../deploy/addons/helm-tiller/"
    target = "content/helm-tiller/"
  [[module.mounts]]
    source = "../deploy/addons/istio/"
    target = "content/istio/"
  [[module.mounts]]
    source = "../deploy/addons/ingress-dns/"
    target = "content/ingress-dns/"
  [[module.mounts]]
    source = "../deploy/addons/storage-provisioner-gluster/"
    target = "content/storage-provisioner-gluster/"
  [[module.mounts]]
    source = "../deploy/addons/layouts/"
    target = "layouts"

  [[module.mounts]]
    source = "content/en"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Additional menu items
[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/kubernetes/minikube"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#id = "UA-00000000-0"

# Language configuration
[languages]
[languages.en]
title = "minikube"
description = "minikube is local Kubernetes"
languageName = "English"
weight = 1

[params]
copyright = "The Kubernetes Authors -- "
# The latest release of minikube
latest_release = "1.7.2"

privacy_policy = ""

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/kubernetes/minikube"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = ""

# Specify a value here if your content directory is not in your repo's root directory
github_subdir = "site"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "005331096405080631692:s7c4yfpw9sy"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/kubernetes/minikube/issues/new/choose">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/kubernetes/minikube/issues/new/choose">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Slack"
	url = "https://kubernetes.slack.com/messages/C1F5CT6Q1"
	icon = "fab fa-slack"
    desc = "Chat with other minikube users & developers"
[[params.links.user]]
	name = "minikube-users mailing list"
	url = "https://groups.google.com/forum/#!forum/minikube-users"
	icon = "fas fa-envelope"
	desc = "Interact with the minikube Users here"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/kubernetes/minikube"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "minikube-dev mailing list"
	url = "https://groups.google.com/forum/#!forum/minikube-dev"
	icon = "fa fa-envelope"
	desc = "Contact the minikube Dev's here"
