name: "generate-docs"
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.21.1'
permissions:
  contents: read

jobs:
  generate-docs:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Generate Docs
        id: gendocs
        run: |
          make generate-docs
          c=$(git status --porcelain)
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$c" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.gendocs.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update auto-generated docs and translations
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: gendocs
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update auto-generated docs and translations'
          body: |
            Committing changes resulting from `make generate-docs`.
            This PR is auto-generated by the [gendocs](https://github.com/kubernetes/minikube/blob/master/.github/workflows/docs.yml) CI workflow.

            ```
            ${{ steps.gendocs.outputs.changes }}
            ```
