name: "generate-docs"
on:
  workflow_dispatch:
  push:
    branches:
      - master  
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19'
permissions:
  contents: read

jobs:
  generate-docs:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Generate Docs
        id: gendocs
        run: |
          make generate-docs
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          echo "::set-output name=changes::$c"
      - name: Create PR
        if: ${{ steps.gendocs.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@18f90432bedd2afd6a825469ffd38aa24712a91d
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update auto-generated docs and translations
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: gendocs
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update auto-generated docs and translations'
          body: |
            Committing changes resulting from `make generate-docs`.
            This PR is auto-generated by the [gendocs](https://github.com/kubernetes/minikube/blob/master/.github/workflows/docs.yml) CI workflow.

            ```
            ${{ steps.gendocs.outputs.changes }}
            ```
