name: "go-mod-tidy"
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.25.5'
permissions:
  contents: read

jobs:
  go-mod-tidy:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{env.GO_VERSION}}
          cache: true
      - name: Tidy Go Modules
        id: gmodtidy
        run: make gomodtidy
      - name: fmt
        id: fmt
        run: make fmt
      - name: goimports in place
        id: goimport
        run: make imports
      - name: Git Changes
        id: gitchanges
        run: |
          c=$(git status --porcelain)
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$c" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.gitchanges.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update auto-generated docs and translations
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: gomodtidy
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'build: go mod tidy'
          body: |
            Committing changes resulting from 
            - `make gomodtidy`
            - `make fmt`
            - `make imports`
            
            This PR is auto-generated by the [gendocs](https://github.com/kubernetes/minikube/blob/master/.github/workflows/go-mod-tidy.yml) CI workflow that runs on every push to master.

            ```
            ${{ steps.gitchanges.outputs.changes }}
            ```
