name: "update-leaderboard"
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - 'v*-beta.*'
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.22.4'
permissions:
  contents: read

jobs:
  update-leaderboard:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Update Leaderboard
        id: leaderboard
        run: |
          make update-leaderboard
          c=$(git status --porcelain)
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$c" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.MINIKUBE_BOT_PAT }}
      - name: Create PR
        if: ${{ steps.leaderboard.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Add leaderboard for ${{ github.ref_name }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: leaderboard
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Post-release: Add leaderboard for ${{ github.ref_name }}'
          body: |
            Committing changes resulting from `make update-leaderboard`.
            This PR is auto-generated by the [update-leaderboard](https://github.com/kubernetes/minikube/blob/master/.github/workflows/leaderboard.yml) CI workflow.

            ```
            ${{ steps.leaderboard.outputs.changes }}
            ```
