name: "update-leaderboard-all-time"
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - 'v*-beta.*'
  release:
    types: [published]
env:
  GO_VERSION: '1.17.6'
jobs:
  update-leaderboard-all-time:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
          stable: true
      - name: Update Leaderboard All-time
        id: leaderboard
        run: |
          make update-leaderboard-all-time
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          echo "::set-output name=changes::$c"
        env:
          GITHUB_TOKEN: ${{ secrets.MINIKUBE_BOT_PAT }}
      - name: Create PR
        if: ${{ steps.leaderboard.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update all-time leaderboard
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: leaderboard-all-time
          base: master
          delete-branch: true
          title: 'Update leaderboard all-time'
          body: |
            Committing changes resulting from `make update-leaderboard-all-time`.
            This PR is auto-generated by the [update-leaderboard-all-time](https://github.com/kubernetes/minikube/blob/master/.github/workflows/leaderboard-all-time.yml) CI workflow.

            ```
            ${{ steps.leaderboard.outputs.changes }}
            ```
