name: "update-leaderboard"
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - 'v*-beta.*'
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.2'
permissions:
  contents: read

jobs:
  update-leaderboard:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Update Leaderboard
        id: leaderboard
        run: |
          make update-leaderboard
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          echo "::set-output name=changes::$c"
        env:
          GITHUB_TOKEN: ${{ secrets.MINIKUBE_BOT_PAT }}
      - name: Create PR
        if: ${{ steps.leaderboard.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update leaderboard
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: leaderboard
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update leaderboard'
          body: |
            Committing changes resulting from `make update-leaderboard`.
            This PR is auto-generated by the [update-leaderboard](https://github.com/kubernetes/minikube/blob/master/.github/workflows/leaderboard.yml) CI workflow.

            ```
            ${{ steps.leaderboard.outputs.changes }}
            ```
