name: Generate SBOM
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  generate_sbom_action:
    runs-on: ubuntu-latest
    name: Install bom and generate SBOM
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@841d76a188a7c121231a863572e27012805715a2 # main
      - name: Generage SBOM
        run: |
          bom generate -o minikube_${{github.ref_name}}_sbom.spdx \
          --dirs=.\
      - name: Upload SBOM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{github.ref_name}} minikube_${{github.ref_name}}_sbom.spdx
