name: Sync docker images of minikube to Alibaba Cloud
on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.25.1'
permissions:
  contents: read

jobs:
  sync-images:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./image-syncer
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          repository: denverdino/image-syncer
          path: ./image-syncer

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Build
        run: make

      - name: Synchronize images to Alibaba Cloud Container Registry Service
        env:
          ACR_USER: ${{ secrets.ALIBABA_CLOUD_ACR_USER }}
          ACR_PASSWORD: ${{ secrets.ALIBABA_CLOUD_ACR_PASSWORD }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

        run: ./image-syncer --auth=auth.json --images=images.json --days=2 --proc=2
