name: "time-to-k8s Public Chart"
on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.2'
permissions:
  contents: read

jobs:
  time-to-k8s-public-chart-docker:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Benchmark time-to-k8s for Docker driver with Docker runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh docker docker
      - name: Benchmark time-to-k8s for Docker driver with containerd runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh docker containerd
  time-to-k8s-public-chart-virtualbox:
    if: github.repository == 'kubernetes/minikube'
    runs-on: macos-12
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Install kubectl
        shell: bash
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl"
          sudo install kubectl /usr/local/bin/kubectl
          kubectl version --client=true
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Disable firewall
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
      - name: Benchmark time-to-k8s for VirtualBox driver with Docker runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh virtualbox docker
      - name: Benchmark time-to-k8s for VirtualBox driver with containerd runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh virtualbox containerd
