name: "time-to-k8s Public Chart"
on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.18.1'
permissions:
  contents: read

jobs:
  time-to-k8s-public-chart-docker:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{env.GO_VERSION}}
          stable: true
      - name: Benchmark time-to-k8s for Docker driver with Docker runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh docker docker
      - name: Benchmark time-to-k8s for Docker driver with containerd runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh docker containerd
  time-to-k8s-public-chart-virtualbox:
    if: github.repository == 'kubernetes/minikube'
    runs-on: macos-10.15
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - name: Install kubectl
        shell: bash
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
          sudo install kubectl /usr/local/bin/kubectl
          kubectl version --client=true
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{env.GO_VERSION}}
          stable: true
      - name: Disable firewall
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
      - name: Benchmark time-to-k8s for VirtualBox driver with Docker runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh virtualbox docker
      - name: Benchmark time-to-k8s for VirtualBox driver with containerd runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh virtualbox containerd
