name: "time-to-k8s Public Chart"
on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.23.2'
permissions:
  contents: read

jobs:
  time-to-k8s-public-chart-docker:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Benchmark time-to-k8s for Docker driver with Docker runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh docker docker
      - name: Benchmark time-to-k8s for Docker driver with containerd runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh docker containerd
  time-to-k8s-public-chart-virtualbox:
    if: github.repository == 'kubernetes/minikube'
    runs-on: macos-12
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install kubectl
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/darwin/amd64/kubectl"
          sudo install kubectl /usr/local/bin/kubectl
          kubectl version --client=true
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Disable firewall
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
      - name: Benchmark time-to-k8s for VirtualBox driver with Docker runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh virtualbox docker
      - name: Benchmark time-to-k8s for VirtualBox driver with containerd runtime
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh virtualbox containerd
