name: "time-to-k8s benchmark"
on:
  workflow_dispatch:
  release:
    types: [released]
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.23.4'
permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Checkout submodules
        run: git submodule update --init
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: ${{env.GO_VERSION}}
      - name: time-to-k8s Benchmark
        id: timeToK8sBenchmark
        run: |
          ./hack/benchmark/time-to-k8s/time-to-k8s.sh
          echo "version=$(minikube version --short)" >> "$GITHUB_OUTPUT"
      - name: Create PR
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: add time-to-k8s benchmark for ${{ steps.timeToK8sBenchmark.outputs.version }}
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: addTimeToK8s${{ steps.timeToK8sBenchmark.outputs.version }}
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: "Post-release: Add time-to-k8s benchmark for ${{ steps.timeToK8sBenchmark.outputs.version }}"
          body: Updating time-to-k8s benchmark as part of the release process
