name: "time-to-k8s benchmark"
on:
  workflow_dispatch:
  release:
    types: [released]
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.25.5'
permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Checkout submodules
        run: git submodule update --init
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version: ${{env.GO_VERSION}}
      - name: time-to-k8s Benchmark
        id: timeToK8sBenchmark
        run: |
          ./hack/benchmark/time-to-k8s/time-to-k8s.sh
          echo "version=$(minikube version --short)" >> "$GITHUB_OUTPUT"
      - name: Create PR
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: add time-to-k8s benchmark for ${{ steps.timeToK8sBenchmark.outputs.version }}
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: addTimeToK8s${{ steps.timeToK8sBenchmark.outputs.version }}
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: "site: Add time-to-k8s benchmark for ${{ steps.timeToK8sBenchmark.outputs.version }} (Post-release)"
          body: Updating time-to-k8s benchmark as part of the release process
