name: "time-to-k8s benchmark"
on:
  pull_request:
    types: [opened]
  #  release:
  #    types: [released]
jobs:
  benchmark:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init
    - uses: actions/setup-go@v2
      with:
          go-version: 1.16.5
          stable: true
    - name: Benchmark
      run: |
          ./hack/benchmark/time-to-k8s/time-to-k8s.sh ${{ secrets.MINIKUBE_BOT_PAT }}
