name: "time-to-k8s Public Chart"
on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.17.3'
jobs:
  time-to-k8s-public-chart:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
          stable: true
      - name: Benchmark time-to-k8s for Docker
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh docker
      - name: Benchmark time-to-k8s for Containerd
        run: |
          ./hack/benchmark/time-to-k8s/public-chart/public-chart.sh containerd
