name: Translations Validation
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "translations/**"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.20.2'
permissions:
  contents: read

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version: ${{env.GO_VERSION}}
          cache: true
          cache-dependency-path: ./go.sum
      - name: Install libvirt
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev
      - name: Download Dependencies
        run: go mod download
      - name: Unit Test
        env:
          TESTSUITE: unittest
        run: make test
        continue-on-error: false
