name: Translations Validation
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "translations/**"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.24.6'
permissions:
  contents: read

jobs:
  unit_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Install libvirt
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev
      - name: Download Dependencies
        run: go mod download
      - name: Unit Test
        env:
          TESTSUITE: unittest
        run: make test
        continue-on-error: false
