name: Translations Validation
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "translations/**"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.18.3'
permissions:
  contents: read

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Install libvirt
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev
      - name: Download Dependencies
        run: go mod download
      - name: Unit Test
        env:
          TESTSUITE: unittest
        run: make test
        continue-on-error: false
