name: "update-cri-o-version"
on:
  workflow_dispatch:
  # Uncomment after crictl/cri-o issue resolved: https://github.com/kubernetes/minikube/issues/18359
  # schedule:
    # every Friday at around 3 am pacific/10 am UTC
    # - cron: "0 10 * * 5"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.23.4'
permissions:
  contents: read

jobs:
  bump-cri-o-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump cri-o Version
        id: bumpCrio
        run: |
          echo "OLD_VERSION=$(DEP=cri-o make get-dependency-version)" >> "$GITHUB_OUTPUT"
          make update-cri-o-version
          echo "NEW_VERSION=$(DEP=cri-o make get-dependency-version)" >> "$GITHUB_OUTPUT"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        id: createPR
        if: ${{ steps.bumpCrio.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Kicbase/ISO: Update cri-o from ${{ steps.bumpCrio.outputs.OLD_VERSION }} to ${{ steps.bumpCrio.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_cri-o_version
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Kicbase/ISO: Update cri-o from ${{ steps.bumpCrio.outputs.OLD_VERSION }} to ${{ steps.bumpCrio.outputs.NEW_VERSION }}'
          body: |
            The cri-o project released a [new version](https://github.com/cri-o/cri-o/releases)

            This PR was auto-generated by `make update-cri-o-version` using [update-cri-o-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-cri-o-version.yml) CI Workflow.
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        if: ${{ steps.bumpCrio.outputs.changes != '' }}
        with:
          github-token: ${{ secrets.MINIKUBE_BOT_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.createPR.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ok-to-build-image'
            })
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        if: ${{ steps.bumpCrio.outputs.changes != '' }}
        with:
          github-token: ${{ secrets.MINIKUBE_BOT_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.createPR.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ok-to-build-iso'
            })
