name: "update-golang-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 2 am pacific/9 am UTC
    - cron: "0 9 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: 1.16.6
jobs:
  bump-k8s-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
          stable: true
      - name: Bump Golang Versions
        id: bumpGolang
        run: |
          make update-golang-version
          echo "::set-output name=changes::$(git status --porcelain)"
      - name: Create PR
        if: ${{ steps.bumpGolang.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump golang versions
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_golang_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'bump golang version'
          labels: ok-to-test
          body: |
            This PR was auto-generated by `make update-golang-version` using [update-golang-versions.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-golang-version.yml) CI Workflow. 
            Please only merge if all the tests pass and if kubernetes pushed an image for this golang https://github.com/kubernetes/kubernetes/blob/master/build/build-image/cross/VERSION
            
            ${{ steps.bumpk8s.outputs.changes }}

