name: "update-gopogh-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 2 am pacific/9 am UTC
    - cron: "0 9 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.23.4'
permissions:
  contents: read

jobs:
  bump-gopogh-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump gopogh Versions
        id: bumpGopogh
        run: |
          echo "OLD_VERSION=$(DEP=gopogh make get-dependency-version)" >> "$GITHUB_OUTPUT"
          make update-gopogh-version
          echo "NEW_VERSION=$(DEP=gopogh make get-dependency-version)" >> "$GITHUB_OUTPUT"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpGopogh.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'CI: Update gopogh from ${{ steps.bumpGopogh.outputs.OLD_VERSION }} to ${{ steps.bumpGopogh.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_gopogh_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'CI: Update gopogh from ${{ steps.bumpGopogh.outputs.OLD_VERSION }} to ${{ steps.bumpGopogh.outputs.NEW_VERSION }}'
          body: |
            The gopogh project released a [new version](https://github.com/medyagh/gopogh/releases)

            This PR was auto-generated by `make update-gopogh-version` using [update-gopogh-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-gopogh-version.yml) CI Workflow.
