name: "update-docsy-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.3'
permissions:
  contents: read

jobs:
  bump-docsy-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{env.GO_VERSION}}
          cache: true
          cache-dependency-path: ./go.sum
      - name: Bump Docsy version
        id: bumpDocsy
        run: |
          make update-docsy-version
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.bumpDocsy.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump docsy version
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_docsy_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'bump docsy version'
          labels: ok-to-test
          body: |
            Docsy project released a [new version](https://github.com/google/docsy/releases),

            This PR was auto-generated by `make update-docsy-version` using [update-docsy-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-docsy-version.yml) CI Workflow.
