name: "update-gopogh-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 2 am pacific/9 am UTC
    - cron: "0 9 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.2'
permissions:
  contents: read

jobs:
  bump-gopogh-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump gopogh Versions
        id: bumpGopogh
        run: |
          make update-gopogh-version
          echo "::set-output name=changes::$(git status --porcelain)"
      - name: Create PR
        if: ${{ steps.bumpGopogh.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@ad43dccb4d726ca8514126628bec209b8354b6dd
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump gopogh versions
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_gopogh_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'bump gopogh version'
          labels: ok-to-test
          body: |
            Gopogh Project released a [new version](https://github.com/medyagh/gopogh/releases),

            This PR was auto-generated by `make update-gopogh-version` using [update-gopogh-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-gopogh-version.yml) CI Workflow.
