name: "update-inspektor-gadget-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.22.0'
permissions:
  contents: read

jobs:
  bump-inspektor-gadget-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Bump inspektor-gadget version
        id: bumpInspektorGadget
        run: |
          echo "OLD_VERSION=$(DEP=inspektor-gadget make get-dependency-version)" >> "$GITHUB_OUTPUT"
          make update-inspektor-gadget-version
          echo "NEW_VERSION=$(DEP=inspektor-gadget make get-dependency-version)" >> "$GITHUB_OUTPUT"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpInspektorGadget.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Addon inspektor-gadget: Update inspektor-gadget image from ${{ steps.bumpInspektorGadget.outputs.OLD_VERSION }} to ${{ steps.bumpInspektorGadget.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_inspektor_gadget_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Addon inspektor-gadget: Update inspektor-gadget image from ${{ steps.bumpInspektorGadget.outputs.OLD_VERSION }} to ${{ steps.bumpInspektorGadget.outputs.NEW_VERSION }}'
          labels: ok-to-test
          body: |
            The inspektor-gadget project released a [new version](https://github.com/inspektor-gadget/inspektor-gadget)

            This PR was auto-generated by `make update-inspektor-gadget-version` using [update-inspektor-gadget-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-inspektor-gadget-version.yml) CI Workflow.
