name: "update-golint-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19'
permissions:
  contents: read

jobs:
  bump-golint-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump Golint Versions
        id: bumpGolint
        run: |
          make update-golint-version
          echo "::set-output name=changes::$(git status --porcelain)"
      - name: Create PR
        if: ${{ steps.bumpGolint.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@18f90432bedd2afd6a825469ffd38aa24712a91d
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump golint versions
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_golint_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'bump golint version'
          labels: ok-to-test
          body: |
            Golangci-lint Project release a [new version](https://github.com/golangci/golangci-lint/releases),

            This PR was auto-generated by `make update-golint-version` using [update-golint-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-golint-version.yml) CI Workflow. 

                   
            
            
