name: "update-kindnetd-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.23.2'
permissions:
  contents: read
jobs:
  bump-kindnetd-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump kindnetd version
        id: bumpKindnetd
        run: |
          echo "OLD_VERSION=$(DEP=kindnetd make get-dependency-version)" >> "$GITHUB_OUTPUT"
          make update-kindnetd-version
          echo "NEW_VERSION=$(DEP=kindnetd make get-dependency-version)" >> "$GITHUB_OUTPUT"
          c=$(git status --porcelain)
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$c" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpKindnetd.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'CNI: Update kindnetd from ${{ steps.bumpKindnetd.outputs.OLD_VERSION }} to ${{ steps.bumpKindnetd.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_kindnetd_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'CNI: Update kindnetd from ${{ steps.bumpKindnetd.outputs.OLD_VERSION }} to ${{ steps.bumpKindnetd.outputs.NEW_VERSION }}'
          labels: ok-to-test
          body: |
            A new version of the kind/kindnetd image was released

            This PR was auto-generated by `make update-kindnetd-version` using [update-kindnetd-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-kindnetd-version.yml) CI Workflow.
