name: "update-nvidia-device-plugin-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.25.5'
permissions:
  contents: read

jobs:
  bump-nvidia-device-plugin-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump nvidia-device-plugin version
        id: bumpNvidiaDevicePlugin
        run: |
          echo "OLD_VERSION=$(DEP=nvidia-device-plugin make get-dependency-version)" >> "$GITHUB_OUTPUT"
          make update-nvidia-device-plugin-version
          echo "NEW_VERSION=$(DEP=nvidia-device-plugin make get-dependency-version)" >> "$GITHUB_OUTPUT"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpNvidiaDevicePlugin.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Addon nvidia-device-plugin: Update nvidia/k8s-device-plugin image from ${{ steps.bumpNvidiaDevicePlugin.outputs.OLD_VERSION }} to ${{ steps.bumpNvidiaDevicePlugin.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_nvidia_device_plugin_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Addon nvidia-device-plugin: Update nvidia/k8s-device-plugin image from ${{ steps.bumpNvidiaDevicePlugin.outputs.OLD_VERSION }} to ${{ steps.bumpNvidiaDevicePlugin.outputs.NEW_VERSION }}'
          labels: ok-to-test
          body: |
            The [k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin) project released a new k8s-device-plugin image

            This PR was auto-generated by `make update-nvidia-device-plugin-version` using [update-nvidia-device-plugin-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-nvidia-device-plugin-version.yml) CI Workflow.
