name: "update-nerdctl-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.21.1'
permissions:
  contents: read

jobs:
  bump-nerdctl-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Bump nerdctl Version
        id: bumpNerdctl
        run: |
          echo "OLD_VERSION=$(DEP=nerdctl make get-dependency-version)" >> $GITHUB_OUTPUT
          make update-nerdctl-version
          echo "NEW_VERSION=$(DEP=nerdctl make get-dependency-version)" >> $GITHUB_OUTPUT
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        id: createPR
        if: ${{ steps.bumpNerdctl.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Kicbase/ISO: Update nerdctl from ${{ steps.bumpNerdctl.outputs.OLD_VERSION }} to ${{ steps.bumpNerdctl.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_nerdctl_version
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Kicbase/ISO: Update nerdctl from ${{ steps.bumpNerdctl.outputs.OLD_VERSION }} to ${{ steps.bumpNerdctl.outputs.NEW_VERSION }}'
          body: |
            The nerdctl project released a [new version](https://github.com/containerd/nerdctl/releases)

            This PR was auto-generated by `make update-nerdctl-version` using [update-nerdctl-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-nerdctl-version.yml) CI Workflow.
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        if: ${{ steps.bumpNerdctl.outputs.changes != '' }}
        with:
          github-token: ${{ secrets.MINIKUBE_BOT_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.createPR.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ok-to-build-image'
            })
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        if: ${{ steps.bumpNerdctl.outputs.changes != '' }}
        with:
          github-token: ${{ secrets.MINIKUBE_BOT_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.createPR.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ok-to-build-iso'
            })
