name: "update-kubeadm-constants"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around midnight pacific/7 am UTC
    - cron: "0 6 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.2'
permissions:
  contents: read

jobs:
  bump-k8s-versions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump Kubeadm Constants for Kubernetes Images
        id: bumpKubAdmConsts
        run: |
          make update-kubeadm-constants
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          echo "::set-output name=changes::$c"
      - name: Create PR
        if: ${{ steps.bumpKubAdmConsts.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@ad43dccb4d726ca8514126628bec209b8354b6dd
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: update image constants for kubeadm images
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_kubeadm_constants
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Bump kubeadm constants for kubernetes images'
          labels: ok-to-test
          body: |
            This PR was auto-generated by `make update-kubeadm-constants` using [update-kubeadm-constants.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-kubeadm-constants.yml) CI Workflow.
            Please only merge if all the tests pass.
            
            ```
            ${{ steps.bumpKubAdmConsts.outputs.changes }}
            ```
