name: "update-docsy-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.23.2'
permissions:
  contents: read

jobs:
  bump-docsy-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump Docsy version
        id: bumpDocsy
        run: |
          echo "NEW_VERSION=$(make update-docsy-version)" >> "$GITHUB_OUTPUT"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpDocsy.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'site: Update docsy version to ${{ steps.bumpDocsy.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_docsy_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'site: Update docsy version to ${{ steps.bumpDocsy.outputs.NEW_VERSION }}'
          body: |
            Docsy project released a [new version](https://github.com/google/docsy/releases),

            This PR was auto-generated by `make update-docsy-version` using [update-docsy-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-docsy-version.yml) CI Workflow.
