name: "update-headlamp-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.25.5'
permissions:
  contents: read

jobs:
  bump-headlamp-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump Headlamp version
        id: bumpHeadlamp
        run: |
          echo "OLD_VERSION=$(DEP=headlamp make get-dependency-version)" >> "$GITHUB_OUTPUT"
          make update-headlamp-version
          echo "NEW_VERSION=$(DEP=headlamp make get-dependency-version)" >> "$GITHUB_OUTPUT"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpHeadlamp.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Addon Headlamp: Update Headlamp image from ${{ steps.bumpHeadlamp.outputs.OLD_VERSION }} to ${{ steps.bumpHeadlamp.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_headlamp_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Addon Headlamp: Update Headlamp image from ${{ steps.bumpHeadlamp.outputs.OLD_VERSION }} to ${{ steps.bumpHeadlamp.outputs.NEW_VERSION }}'
          labels: ok-to-test
          body: |
            The [Headlamp](https://github.com/headlamp-k8s/headlamp) project released a new Headlamp image

            This PR was auto-generated by `make update-headlamp-version` using [update-headlamp-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-headlamp-version.yml) CI Workflow.
