name: "update-kubernetes-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 1 am pacific/8 am UTC
    - cron: "0 8 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.2'
permissions:
  contents: read

jobs:
  bump-k8s-versions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump Kubernetes Versions
        id: bumpk8s
        run: |
          t=$(make update-kubernetes-version)
          t=$(echo $t | head -n 1)
          echo "::set-output name=title::$t"
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          echo "::set-output name=changes::$c"
      - name: Create PR
        if: ${{ steps.bumpk8s.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@ad43dccb4d726ca8514126628bec209b8354b6dd
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump default/newest kubernetes versions
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_k8s_versions
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: "${{ steps.bumpk8s.outputs.title }}"
          labels: ok-to-test
          body: |
            This PR was auto-generated by `make update-kubernetes-version` using [update-k8s-versions.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-k8s-versions.yml) CI Workflow.
            Please only merge if all the tests pass.

            ```
            ${{ steps.bumpk8s.outputs.changes }}
            ```
