name: "update-gcp-auth-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.21.1'
permissions:
  contents: read

jobs:
  bump-gcp-auth-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Bump gcp-auth version
        id: bumpGCPAuth
        run: |
          echo "OLD_VERSION=$(DEP=gcp-auth make get-dependency-version)" >> $GITHUB_OUTPUT
          make update-gcp-auth-version
          echo "NEW_VERSION=$(DEP=gcp-auth make get-dependency-version)" >> $GITHUB_OUTPUT
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.bumpGCPAuth.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Addon gcp-auth: Update k8s-minikube/gcp-auth-webhook image from ${{ steps.bumpGCPAuth.outputs.OLD_VERSION }} to ${{ steps.bumpGCPAuth.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_gcp_auth_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Addon gcp-auth: Update k8s-minikube/gcp-auth-webhook image from ${{ steps.bumpGCPAuth.outputs.OLD_VERSION }} to ${{ steps.bumpGCPAuth.outputs.NEW_VERSION }}'
          labels: ok-to-test
          body: |
            The gcp-auth-webhook project released a [new version](https://github.com/GoogleContainerTools/gcp-auth-webhook)

            This PR was auto-generated by `make update-gcp-auth-version` using [update-gcp-auth-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-gcp-auth-version.yml) CI Workflow.
