name: "update-ubuntu-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.20.3'
permissions:
  contents: read

jobs:
  bump-ubuntu-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Bump Ubuntu version
        id: bumpUbuntu
        run: |
          make update-ubuntu-version
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$c" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        id: createPR
        if: ${{ steps.bumpUbuntu.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: update ubuntu:focal image version
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_ubuntu_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Kicbase: Bump ubuntu:focal image version'
          body: |
            The ubuntu:focal image released a new version

            This PR was auto-generated by `make update-ubuntu-version` using [update-ubuntu-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-ubuntu-version.yml) CI Workflow.
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          github-token: ${{ secrets.MINIKUBE_BOT_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.createPR.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ok-to-build-image'
            })
