name: "update-kubernetes-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 1 am pacific/8 am UTC
    - cron: "0 8 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.25.5'
permissions:
  contents: read

jobs:
  bump-k8s-versions:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump Kubernetes Versions
        id: bumpk8s
        run: |
          t=$(make update-kubernetes-version)
          t=$(echo $t | head -n 1)
          echo "title=$t" >> "$GITHUB_OUTPUT"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpk8s.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump default/newest kubernetes versions
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_k8s_versions
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: "${{ steps.bumpk8s.outputs.title }}"
          labels: ok-to-test,kind/feature
          body: |
            This PR was auto-generated by `make update-kubernetes-version` using [update-k8s-versions.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-k8s-versions.yml) CI Workflow.
            Please only merge if all the tests pass.

            ```
            ${{ steps.bumpk8s.outputs.changes }}
            ```
