name: "update-volcano-version"
on:
  workflow_dispatch:
  schedule:
    # every Saturday at 1:00 Pacific/8:00 UTC
    - cron: "0 8 * * 6"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.25.5'
permissions:
  contents: read

jobs:
  bump-volcano-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Bump volcano version
        id: bumpVolcano
        run: |
          echo "OLD_VERSION=$(DEP=volcano make get-dependency-version)" >> "$GITHUB_OUTPUT"
          make update-volcano-version
          echo "NEW_VERSION=$(DEP=volcano make get-dependency-version)" >> "$GITHUB_OUTPUT"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: ${{ steps.bumpVolcano.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: 'Addon Volcano: Update volcano images from ${{ steps.bumpVolcano.outputs.OLD_VERSION }} to ${{ steps.bumpVolcano.outputs.NEW_VERSION }}'
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_volcano_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Addon Volcano: Update volcano images from ${{ steps.bumpVolcano.outputs.OLD_VERSION }} to ${{ steps.bumpVolcano.outputs.NEW_VERSION }}'
          labels: ok-to-test
          body: |
            The [Volcano](https://github.com/volcano-sh/volcano) project made a new release

            This PR was auto-generated by `make update-volcano-version` using [update-volcano-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-volcano-version.yml) CI Workflow.
