on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  vexctl:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: openvex/generate-vex@31b415924ea0d72ed5f2640f1dee59dea6c2770b
        name: Run vexctl
        with:
          product: pkg:golang/k8s.io/minikube@${{ env.RELEASE_VERSION }}

