name: "update-yearly-leaderboard"
on:
  workflow_dispatch:
  schedule:
    # The 2nd of every month
    - cron: "0 0 2 * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.2'
permissions:
  contents: read

jobs:
  update-yearly-leaderboard:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Update Yearly Leaderboard
        id: yearlyLeaderboard
        run: |
          make update-yearly-leaderboard
          echo "::set-output name=changes::$(git status --porcelain)"
        env:
          GITHUB_TOKEN: ${{ secrets.MINIKUBE_BOT_PAT }}
      - name: Create PR
        if: ${{ steps.yearlyLeaderboard.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@ad43dccb4d726ca8514126628bec209b8354b6dd
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update yearly leaderboard
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: yearly-leaderboard
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update Yearly Leaderboard'
          body: |
            Committing changes resulting from `make update-yearly-leaderboard`.
            This PR is auto-generated by the [update-yearly-leaderboard](https://github.com/kubernetes/minikube/blob/master/.github/workflows/yearly-leaderboard.yml) CI workflow.
