name: "update-yearly-leaderboard"
on:
  workflow_dispatch:
  schedule:
    # The 2nd of every month
    - cron: "0 0 2 * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.21.1'
permissions:
  contents: read

jobs:
  update-yearly-leaderboard:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Update Yearly Leaderboard
        id: yearlyLeaderboard
        run: |
          make update-yearly-leaderboard
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.MINIKUBE_BOT_PAT }}
      - name: Create PR
        if: ${{ steps.yearlyLeaderboard.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update yearly leaderboard
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: yearly-leaderboard
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update Yearly Leaderboard'
          body: |
            Committing changes resulting from `make update-yearly-leaderboard`.
            This PR is auto-generated by the [update-yearly-leaderboard](https://github.com/kubernetes/minikube/blob/master/.github/workflows/yearly-leaderboard.yml) CI workflow.
