name: "update-yearly-leaderboard"
on:
  workflow_dispatch:
  schedule:
    # The 2nd of every month
    - cron: "0 0 2 * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.18.3'
permissions:
  contents: read

jobs:
  update-yearly-leaderboard:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Update Yearly Leaderboard
        id: yearly-leaderboard
        run: |
          make update-yearly-leaderboard
        env:
          GITHUB_TOKEN: ${{ secrets.MINIKUBE_BOT_PAT }}
      - name: Create PR
        if: ${{ steps.leaderboard.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update yearly leaderboard
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: yearly-leaderboard
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update Yearly Leaderboard'
          body: |
            Committing changes resulting from `make update-yearly-leaderboard`.
            This PR is auto-generated by the [update-yearly-leaderboard](https://github.com/kubernetes/minikube/blob/master/.github/workflows/yearly-leaderboard.yml) CI workflow.
