name: "update-yearly-leaderboard"
on:
  workflow_dispatch:
  schedule:
    # The 2nd of every month
    - cron: "0 0 2 * *"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.23.2'
permissions:
  contents: read

jobs:
  update-yearly-leaderboard:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Update Yearly Leaderboard
        id: yearlyLeaderboard
        run: |
          sudo apt install ncal
          make update-yearly-leaderboard
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$(git status --porcelain)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.MINIKUBE_BOT_PAT }}
      - name: Create PR
        if: ${{ steps.yearlyLeaderboard.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update yearly leaderboard
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: yearly-leaderboard
          branch-suffix: short-commit-hash
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update Yearly Leaderboard'
          body: |
            Committing changes resulting from `make update-yearly-leaderboard`.
            This PR is auto-generated by the [update-yearly-leaderboard](https://github.com/kubernetes/minikube/blob/master/.github/workflows/yearly-leaderboard.yml) CI workflow.
